// This file is generated by Slice Machine. Update with care!

import BigImage from './BigImage';
import ImageTemplate from './ImageTemplate';
import Logos from './Logos';
import TextTemplate from './TextTemplate';

export {
	BigImage,
	ImageTemplate,
	Logos,
	TextTemplate,
};

export const components = {
	big_image: BigImage,
	image_template: ImageTemplate,
	logos: Logos,
	text_template: TextTemplate,
};
