// This file is generated by Slice Machine. Update with care!

import ImageTemplate from './ImageTemplate';
import TextTemplate from './TextTemplate';

export {
	ImageTemplate,
	TextTemplate,
};

export const components = {
	image_template: ImageTemplate,
	text_template: TextTemplate,
};
